// Source of truth: products/atlas/atlas-os/lib/constants/payors.ts
// Regenerated by scripts/sync-payors.mjs — do not hand-edit the
// commercial/medicare/medicaid arrays below (heading/footnote are preserved
// as-is by the sync script; edit those directly, they won't be overwritten).
// Atlas Enrollment and Atlas OS have no shared code dependency (see
// package-docs/ATLAS_ENROLLMENT_OVERVIEW.md) — this file is a synced copy,
// not an import. Run `pnpm sync:payors` after touching atlas-os's list.

export const insuranceNetworks = {
  heading: "Payers we work with.",
  commercial: ["BCBSM", "Aetna", "Optum / UnitedHealthcare", "Humana", "HAP / ASR", "Priority Health"],
  medicare: ["Medicare WPS/GHA"],
  medicaid: {
    label: "Medicaid (Michigan)",
    plans: ["CHAMPS / Michigan Medicaid", "Meridian (managed Medicaid)", "Molina (managed Medicaid)", "McLaren (managed Medicaid)"]
  },
  // Keep this honest — reflect actual current coverage, not aspirational
  // reach. See reference/CONTENT_STRATEGY.md.
  footnote: "Currently serving Michigan practices, with Medicare and commercial payer reach beyond the state."
};
