// Logo grid data for the homepage Insurance Networks section. This is a
// hand-curated presentation layer on top of content/home/insurance-networks.ts
// (which is auto-regenerated by scripts/sync-payors.mjs and must not be
// hand-edited — see that file's own header). This file is NOT auto-synced:
// re-check it against insurance-networks.ts whenever `pnpm sync:payors` runs
// and the payer list actually changes.
//
// Every entry's logoSrc was visually verified against the real payer brand
// before being added here — one asset in public/atlas_logos/ (BCBS.png) was
// found to actually be the Anthem logo (a different, unrelated Blue Cross
// Blue Shield licensee — not Michigan's) and is deliberately NOT used below.
// BCBSM has no verified logo asset yet and renders as a text-only card.
//
// `href` is set ONLY when a real payer landing page exists (SEO Phase 2 —
// package-docs/reference/SEO_STRATEGY.md § Phase 2) — never link to a page
// that doesn't exist yet.
export interface PayerLogoEntry {
  name: string;
  alt: string;
  logoSrc?: string;
  href?: string;
}

export interface PayerLogoCategory {
  label: string;
  payers: PayerLogoEntry[];
}

export const payerLogoCategories: PayerLogoCategory[] = [
  {
    label: "Commercial",
    payers: [
      {
        name: "BCBSM",
        // No verified logo asset — see file header. Do not add BCBS.png here;
        // it's the Anthem logo, a different Blue Cross Blue Shield licensee.
        // alt left empty since there's no image to describe.
        alt: "",
        href: "/bcbsm-credentialing"
      },
      { name: "Aetna", alt: "Aetna logo", logoSrc: "/atlas_logos/Aetna.png" },
      { name: "Optum", alt: "Optum logo", logoSrc: "/atlas_logos/Optum.png" },
      {
        name: "UnitedHealthcare",
        alt: "UnitedHealthcare logo",
        logoSrc: "/atlas_logos/UnitedHealthcare_(logo).svg"
      },
      { name: "Humana", alt: "Humana logo", logoSrc: "/atlas_logos/Humana.png" },
      { name: "HAP / ASR", alt: "Health Alliance Plan logo", logoSrc: "/atlas_logos/HAP.png" },
      { name: "Priority Health", alt: "Priority Health logo", logoSrc: "/atlas_logos/PriorityHealth.png" }
    ]
  },
  {
    label: "Medicare",
    payers: [{ name: "Medicare WPS/GHA", alt: "Medicare logo", logoSrc: "/atlas_logos/Medicare.png" }]
  },
  {
    label: "Medicaid (Michigan)",
    payers: [
      {
        name: "CHAMPS / Michigan Medicaid",
        alt: "Michigan Department of Health and Human Services logo",
        logoSrc: "/atlas_logos/MDHHS.png"
      },
      // No verified logo asset for Meridian — text-only card, per "use logos
      // only where the asset exists."
      { name: "Meridian (managed Medicaid)", alt: "" },
      { name: "Molina (managed Medicaid)", alt: "Molina Healthcare logo", logoSrc: "/atlas_logos/Molina.png" },
      { name: "McLaren (managed Medicaid)", alt: "McLaren Health Care logo", logoSrc: "/atlas_logos/McLaren.png" }
    ]
  }
];
