// Logo grid data for the homepage Insurance Networks section. This is a
// hand-curated presentation layer on top of content/home/insurance-networks.ts
// (which is auto-regenerated by scripts/sync-payors.mjs and must not be
// hand-edited — see that file's own header). This file is NOT auto-synced:
// re-check it against insurance-networks.ts whenever `pnpm sync:payors` runs
// and the payer list actually changes.
//
// Every entry's logoSrc was visually verified against the real payer brand
// before being added here — an earlier asset in public/atlas_logos/
// (BCBS.png) was found to actually be the Anthem logo (a different,
// unrelated Blue Cross Blue Shield licensee — not Michigan's) and was never
// used. It has since been replaced with a verified correct asset (see BCBSM
// entry below).
//
// `href` is set ONLY when a real payer landing page exists (SEO Phase 2 —
// package-docs/reference/SEO_STRATEGY.md § Phase 2) — never link to a page
// that doesn't exist yet.
export interface PayerLogoEntry {
  name: string;
  alt: string;
  logoSrc?: string;
  href?: string;
}

export interface PayerLogoCategory {
  label: string;
  payers: PayerLogoEntry[];
}

export const payerLogoCategories: PayerLogoCategory[] = [
  {
    label: "Commercial",
    payers: [
      {
        name: "BCBSM",
        alt: "Blue Cross Blue Shield of Michigan logo",
        logoSrc: "/atlas_logos/Blue_Cross_Blue_Shield_of_Michigan_(BCBSM)_logo.png",
        href: "/bcbsm-credentialing"
      },
      { name: "Aetna", alt: "Aetna logo", logoSrc: "/atlas_logos/Aetna.png", href: "/aetna-provider-enrollment" },
      { name: "Optum", alt: "Optum logo", logoSrc: "/atlas_logos/Optum.png", href: "/optum-credentialing" },
      {
        name: "UnitedHealthcare",
        alt: "UnitedHealthcare logo",
        logoSrc: "/atlas_logos/UnitedHealthcare_(logo).svg",
        // Same page as Optum — one payer entry in the underlying data
        // (content/home/insurance-networks.ts), split into two logo cards
        // per the original design request, but there's only one landing page.
        href: "/optum-credentialing"
      },
      { name: "Humana", alt: "Humana logo", logoSrc: "/atlas_logos/Humana.png", href: "/humana-provider-enrollment" },
      {
        name: "HAP / ASR",
        alt: "Health Alliance Plan logo",
        logoSrc: "/atlas_logos/HAP.png",
        href: "/hap-provider-enrollment"
      },
      {
        name: "Priority Health",
        alt: "Priority Health logo",
        logoSrc: "/atlas_logos/PriorityHealth.png",
        href: "/priority-health-credentialing"
      }
    ]
  },
  {
    label: "Medicare",
    payers: [
      {
        name: "Medicare WPS/GHA",
        alt: "Medicare logo",
        logoSrc: "/atlas_logos/Medicare.png",
        href: "/medicare-provider-enrollment"
      }
    ]
  },
  {
    label: "Medicaid (Michigan)",
    payers: [
      {
        name: "CHAMPS / Michigan Medicaid",
        alt: "Michigan Department of Health and Human Services logo",
        logoSrc: "/atlas_logos/MDHHS.png",
        href: "/michigan-medicaid-champs"
      },
      {
        name: "Meridian (managed Medicaid)",
        alt: "Meridian logo",
        logoSrc: "/atlas_logos/Meridian-RGB.png",
        // Managed Medicaid plans are covered as part of the CHAMPS page,
        // not a separate landing page each — see content/payers/michigan-medicaid.ts
        href: "/michigan-medicaid-champs"
      },
      {
        name: "Molina (managed Medicaid)",
        alt: "Molina Healthcare logo",
        logoSrc: "/atlas_logos/Molina.png",
        href: "/michigan-medicaid-champs"
      },
      {
        name: "McLaren (managed Medicaid)",
        alt: "McLaren Health Care logo",
        logoSrc: "/atlas_logos/McLaren.png",
        href: "/michigan-medicaid-champs"
      }
    ]
  }
];
