#!/usr/bin/env node
// AE-4 (package-docs/GAPS_AND_TASKS.md): regenerates
// content/home/insurance-networks.ts's payer arrays from atlas-os's
// lib/constants/payors.ts — the two products have no shared code
// dependency (see package-docs/ATLAS_ENROLLMENT_OVERVIEW.md), so this is a
// local dev-time sync script a developer runs manually after touching
// atlas-os's payor list, not a build-time/runtime coupling between the two
// deployed apps. Marketing copy (heading/footnote) is preserved as-is —
// only the commercial/medicare/medicaid arrays are regenerated.
//
// Usage: node scripts/sync-payors.mjs [path-to-atlas-os-payors.ts]

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, "../content/home/insurance-networks.ts");
const DEFAULT_SOURCE = resolve(__dirname, "../../../products/atlas-os/lib/constants/payors.ts");
const LOGO_PATH = resolve(__dirname, "../content/home/payer-logos.ts");
const SOURCE_PATH = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_SOURCE;

const STATE_NAMES = { MI: "Michigan" };

function parsePayors(sourceText) {
  const objectMatches = sourceText.match(/\{[^{}]*\}/g) ?? [];
  return objectMatches.map((block) => {
    const get = (key) => block.match(new RegExp(`${key}:\\s*"([^"]+)"`))?.[1];
    return {
      name: get("name"),
      category: get("category"),
      state: get("state")
    };
  }).filter((p) => p.name && p.category);
}

function buildInsuranceNetworks(payors, existingHeading, existingFootnote) {
  const commercial = payors.filter((p) => p.category === "commercial").map((p) => p.name);
  const medicare = payors.filter((p) => p.category === "medicare").map((p) => p.name);
  const medicaid = payors.filter((p) => p.category === "medicaid").map((p) => p.name);
  const managedMedicaid = payors
    .filter((p) => p.category === "managed_medicaid")
    .map((p) => `${p.name} (managed Medicaid)`);
  const medicaidPlans = [...medicaid, ...managedMedicaid];

  const medicaidStates = [...new Set(payors.filter((p) => p.category === "medicaid" || p.category === "managed_medicaid").map((p) => p.state).filter(Boolean))];
  const medicaidLabel = medicaidStates.length === 1
    ? `Medicaid (${STATE_NAMES[medicaidStates[0]] ?? medicaidStates[0]})`
    : "Medicaid";

  return { commercial, medicare, medicaidLabel, medicaidPlans, heading: existingHeading, footnote: existingFootnote };
}

function render({ commercial, medicare, medicaidLabel, medicaidPlans, heading, footnote }) {
  const arr = (items) => `[${items.map((s) => JSON.stringify(s)).join(", ")}]`;
  return `// Source of truth: products/atlas-os/lib/constants/payors.ts
// Regenerated by scripts/sync-payors.mjs — do not hand-edit the
// commercial/medicare/medicaid arrays below (heading/footnote are preserved
// as-is by the sync script; edit those directly, they won't be overwritten).
// Atlas Enrollment and Atlas OS have no shared code dependency (see
// package-docs/ATLAS_ENROLLMENT_OVERVIEW.md) — this file is a synced copy,
// not an import. Run \`pnpm sync:payors\` after touching atlas-os's list.

export const insuranceNetworks = {
  heading: ${JSON.stringify(heading)},
  commercial: ${arr(commercial)},
  medicare: ${arr(medicare)},
  medicaid: {
    label: ${JSON.stringify(medicaidLabel)},
    plans: ${arr(medicaidPlans)}
  },
  // Keep this honest — reflect actual current coverage, not aspirational
  // reach. See reference/CONTENT_STRATEGY.md.
  footnote: ${JSON.stringify(footnote)}
};
`;
}

function main() {
  let sourceText;
  try {
    sourceText = readFileSync(SOURCE_PATH, "utf-8");
  } catch {
    console.warn(
      `[sync-payors] Could not read ${SOURCE_PATH} — atlas-os isn't checked out alongside this repo ` +
      `(expected in the Loggie_OS_Master monorepo layout only). Skipping sync; ` +
      `content/home/insurance-networks.ts is unchanged.`
    );
    process.exit(0);
  }

  const payors = parsePayors(sourceText);
  if (payors.length === 0) {
    console.error(`[sync-payors] Parsed 0 payors from ${SOURCE_PATH} — source format may have changed. Aborting without writing.`);
    process.exit(1);
  }

  const existing = readFileSync(OUTPUT_PATH, "utf-8");
  const existingHeading = existing.match(/heading:\s*"([^"]+)"/)?.[1] ?? "Payers we work with.";
  const existingFootnote = existing.match(/footnote:\s*"([^"]+)"/)?.[1] ?? "";

  const data = buildInsuranceNetworks(payors, existingHeading, existingFootnote);
  writeFileSync(OUTPUT_PATH, render(data));
  console.log(`[sync-payors] Synced ${payors.length} payors from ${SOURCE_PATH} -> ${OUTPUT_PATH}`);

  reportUnrenderedPayors(data);
}

// The file this script writes is no longer what the homepage renders: since
// the text list became a logo grid, InsuranceNetworks.tsx reads its cards from
// content/home/payer-logos.ts and takes only the heading and footnote from
// here. payer-logos.ts is hand-curated (a logo asset has to be visually
// verified against the real payer brand before it is added), so this script
// cannot write it -- but it can refuse to let a payer be synced and silently
// never reach the page, which is exactly what happened when Blue Cross
// Complete of Michigan was added upstream.
// A payer counts as rendered if the grid shows it under any of the names it
// could reasonably carry there. Two mismatches are expected by design and must
// not be reported as gaps: a "(managed Medicaid)" style qualifier this script
// appends, and a slash-joined payer that the grid splits into one card each --
// "Optum / UnitedHealthcare" is a single payor upstream but two cards here, as
// that file's own comment explains.
function isRendered(name, logoSource) {
  const base = name.split(" (")[0].trim();
  const candidates = [base, ...base.split("/").map((part) => part.trim())].filter(
    (candidate) => candidate.length >= 3
  );
  return candidates.some((candidate) => logoSource.includes(candidate));
}

function reportUnrenderedPayors(data) {
  let logoSource;
  try {
    logoSource = readFileSync(LOGO_PATH, "utf-8");
  } catch {
    console.warn(`[sync-payors] Could not read ${LOGO_PATH} -- skipping the render check.`);
    return;
  }

  const listed = [...data.commercial, ...data.medicare, ...data.medicaidPlans];
  const missing = listed.filter((name) => !isRendered(name, logoSource));

  if (missing.length === 0) return;

  console.warn(
    `\n[sync-payors] ${missing.length} payer(s) synced but NOT rendered on the homepage:\n` +
    missing.map((name) => `  - ${name}`).join("\n") +
    `\n\nThe homepage grid is driven by ${LOGO_PATH}, which this script does not\n` +
    `write. Add an entry there (omit logoSrc until a verified asset exists) or\n` +
    `the payer will not appear on the site.\n`
  );
}

main();
